### ISSUE TITLE
Links!

### ISSUE THREAD

**Issue by TrickJoker312** [whos-evan/kazwire#13]
Are there any more links for this site? If so, please link them below. I'd really appreciate it!

**Comment by Ironbrodiet** [comment]
Same!

**Comment by whos-evan** [comment]
I’m working on adding better documentation that may include more official links. However this comes at the risk of them being inaccessible to many students. For now you can join the Discord and use the bot to get official domains. https://discord.gg/kazchat-785577600219086881
