### ISSUE TITLE
can you plz make a video on how to download it I'm so confused 

### ISSUE THREAD

**Issue by tino0321** [whos-evan/kazwire#53]

**Comment by whos-evan** [comment]
https://user-images.githubusercontent.com/72959444/222988769-f24ee8e2-d71a-4778-b76d-c5cdee61b4ca.mp4

**Comment by tino0321** [comment]
on cromebook its blocked how do you download it thou git hub

**Comment by tino0321** [comment]
or can you not

**Comment by whos-evan** [comment]
Please join our Discord for further inquiries. https://discord.com/invite/kazwire
